### ISSUE TITLE
Issues running the db:migrate command (ERROR: getaddrinfo EAI_AGAIN csmm csmm:3306)

### ISSUE THREAD

**Issue by Connor-Knabe** [CatalysmsServerManager/docs#211]
I get the following error when I run the db:migrate command

> ERROR: getaddrinfo EAI_AGAIN csmm csmm:3306
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! csmm@1.17.5 sequelize: `sequelize-cli "db:migrate"`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the csmm@1.17.5 sequelize script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging >output above.

**Comment by niekcandaele** [comment]
Check your .env. It's trying to connect to a database at `csmm:3306`.

if you are using the docker-compose from the repo, this should be `db:3306`.
if you are installing w/o containers, this should be `127.0.0.1:3306` (if the database runs on the same host as where you're executing `db:migrate`)

**Comment by Connor-Knabe** [comment]
Okay maybe that was the fix actually,  I was thinking it might be the password containing special characters but I also changed to localhost around the same time. Will report back. Thanks!

**Comment by niekcandaele** [comment]
Yep, I'm very confident the DNS thing was the issue not the password :wink:
